In [1]:
import numpy
numpy.__version__

'1.18.1'

# Question 1

In [8]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)
arr.dtype
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
<class 'numpy.ndarray'>


# Question 2

In [18]:
import numpy as np
lst1=[]
lst2=[]
for i in range(5):
    x=int(input())
    lst1.append(x)
for j in range(5):
    y=int(input())
    lst2.append(y)

arr1 = np.asarray(lst1)
print("Array1 :",arr1)
arr2 = np.asarray(lst2)
print("Array2 :",arr2)

arr3 = np.concatenate((arr1,arr2))
print("Concatenation array :",arr3)


print("Sorted Array :",np.sort(arr3))

    
    

5
1
7
2
0
4
62
12
90
33
Array1 : [5 1 7 2 0]
Array2 : [ 4 62 12 90 33]
Concatenation array : [ 5  1  7  2  0  4 62 12 90 33]
Sorted Array : [ 0  1  2  4  5  7 12 33 62 90]


# Question 3

In [19]:
import numpy as np

arr = np.array([1,2,3,4,5])


1


In [22]:
print(arr.ndim)

1


In [20]:
print(arr.shape)

(5,)


In [21]:
print(arr.size)

5


In [23]:
print(len(arr))

5


# Question 4

In [24]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question 5

In [25]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  

print("Vertical stacking:\n", np.vstack((a, b))) 
  

print("\nHorizontal stacking:\n", np.hstack((a, b))) 
  
c = [5, 6] 
  

print("\nColumn stacking:\n", np.column_stack((a, c))) 
  

print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [26]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = numpy.unique(number_list, return_counts=True)
frequencies = numpy.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
